name: pynetcf
dependencies:
- hdf5
- numpy
- pandas
- netcdf4
- proj4
- pyproj
- pykdtree
- pip:
  - pygeobase>=0.3.18
  - pygeogrids>=0.1.9
  - pytest-cov==2.2.1
  - coverage==4.5.2
  - pytest==3.8.2

